GET http://localhost:8080/api/employees

###

POST http://localhost:8080/api/addemployee
Content-Type: application/json

{
    "fullName": "Ariana Winters",
    "email": "arianaw15@gmail.com",
    "employmentStatus": true,
    "hourlyRate": 7.50
}